# By convention, the first pseudorule should be called "all"
# We're using the expand() function to create multiple targets
rule all:
	input:
		expand(
			"{greeting}/boot-disk-world.txt",
			greeting = ['hello', 'hola'],
		),

# First real rule, this is using a wildcard called "greeting"
rule multilingual_hello_world:
	output:
		"{greeting}/boot-disk-world.txt",
	resources:
		googlebatch_boot_disk_image="batch-centos",
		googlebatch_boot_disk_type="pd-standard",
		googlebatch_boot_disk_gb=40
	shell:
		"""
		mkdir -p "{wildcards.greeting}"
		sleep 5
		echo "{wildcards.greeting}, World!" > {output}
		"""
