import os

storage:
        provider="gcs",
        max_requests_per_second= None

rule all:
    input:
        "landsat-data.txt.bz2",
        "testdir"

rule copy:
    input:
        storage.gcs("gcs://gcp-public-data-landsat/LC08/01/001/003/LC08_L1GT_001003_20170430_20170501_01_RT/LC08_L1GT_001003_20170430_20170501_01_RT_MTL.txt"),
    output:
        "landsat-data.txt"
    resources:
        mem_mb=100
    run:
        # we could test volume size like this but it is currently unclear what f1-micro instances provide as boot disk size
        #stats = os.statvfs('.')
        #volume_gib = stats.f_bsize * stats.f_blocks / 1.074e9
        #assert volume_gib > 90
        shell("cp {input} {output}")

rule pack:
    input:
        "landsat-data.txt"
    output:
        "landsat-data.txt.bz2"
    conda:
        "env.yml"
    log:
        "logs/pack.log"
    shell:
        "bzip2 -c {input} > {output}; echo successful > {log}"


rule directory:
    output:
        directory("testdir")
    log:
        "logs/directory.log"
    shell:
        "mkdir -p {output}; touch {output}/test.txt"
